server {
    listen 81;
    server_name localhost;
    root /var/www-v2/html/public;
    index index.php;

    otel_span_attr "http.route" $uri;
    otel_span_attr "lab.variant" "keepsuit";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php-v2:9000;
        fastcgi_index index.php;
        # php-v2 では laravel-v2 が /var/www/html にマウントされているので絶対パス固定
        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_param HTTP_TRACEPARENT $http_traceparent;
        fastcgi_param HTTP_TRACESTATE $http_tracestate;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
}
